### ISSUE TITLE
Error when executing the ubuntu script

### ISSUE THREAD

**Issue by xpillons** [Azure/batch-insights#16]
Here is the error I'm getting when running the ubuntu.sh script in a startup task from a pool deployed using custom image.

E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?

**Comment by timotheeguerin** [comment]
Are you running the start task as a pool admin user?

**Comment by xpillons** [comment]
Yes

**Comment by timotheeguerin** [comment]
Which version of Ubuntu is it?

**Comment by xpillons** [comment]
16.04

**Comment by timotheeguerin** [comment]
thanks, will take a look

**Comment by timotheeguerin** [comment]
Should be solved with the go rewrite
