### ISSUE TITLE
Provide a unique script for setup

### ISSUE THREAD

**Issue by xpillons** [Azure/batch-insights#17]
Having to choose the setup script based on OS distro is error prone. It would be great to have a single setup script for Linux.

**Comment by timotheeguerin** [comment]
This is a great idea but would probably go with packaging the app so you not have to install python  and other dependencies. There is however discussion on having this or an alternative in the Batch service which makes wonder if such a investment is worth it.

**Comment by timotheeguerin** [comment]
This should be taken care of with the new go rewrite. One script for linux and one for windows
