### ISSUE TITLE
Hitting chocolatey rate limits

### ISSUE THREAD

**Issue by JimiSmith** [Azure/batch-insights#18]
I'm getting this error when running the startup command on windows low priority nodes

```
Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (429) Too Many Requests."
At line:167 char:3
+   $downloader.DownloadFile($url, $file)
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
 
ERROR: The system cannot find the file specified.
D:\Users\PoolAdmin1469656965\AppData\Local\Temp\chocolatey\chocInstall\chocolatey.zip
```

Looking at the [Chocolatey troubleshooting docs](https://chocolatey.org/docs/troubleshooting#im-getting-a-429-too-many-requests-issue-when-attempting-to-use-the-community-package-repository) I see that there is per IP rate limits which appear to be the cause of this error.

Is there a solution to this?

**Comment by timotheeguerin** [comment]
Are you using CloudService or a VM for the pool? The cloudservice might be reusing the same ip for all VM in the same group of node which might make it to reach 20 per minutes

**Comment by JimiSmith** [comment]
The pool allocation mode is batch service. And there were around 50 VMs in the pool at the time of the error. I can easily see it reaching 20 per minute in that scenario. I'll try again tomorrow and see if the error happens repeatedly.

From what I can tell the only thing chocolatey is used for is to install python. So I guess I can work around the issue by installing python through another mechanism and then following the generic instructions in the readme?

**Comment by timotheeguerin** [comment]
I mean on the pool are you using `cloudServiceConfiguration` or `virtualMachineConfiguration`?
Yes a workaroung would be to install python some other way.
There is also a branch where I rewrote this in go, still need to be fully tested but then it would just require you to download an single file and run it.

**Comment by JimiSmith** [comment]
Sorry, I misunderstood. The pool is using `virtualMachineConfiguration`

**Comment by timotheeguerin** [comment]
Should be solved with the go rewrite
