### ISSUE TITLE
BatchLabs and Azure portal does not show any data

### ISSUE THREAD

**Issue by Gaploid** [Azure/batch-insights#2]
Hi,
I`ve just install appinsight as it said in docs and set env variables but I do not see any data/graphs in BatchLabs and neither in the Azure portal. Is there any way to check/debug that?

**Comment by timotheeguerin** [comment]
Sorry, I completely missed that issue. Can you email me at tiguerin@microsoft.com so we can debug this?

Does it shows this?
![image](https://user-images.githubusercontent.com/1031227/34887699-3d2d89cc-f77c-11e7-9678-5d1f1a1126ff.png)

or the graph are empty?
if empty then you go on a node then check the file `wd/node-stats.log` which should tell you a bit about it

**Comment by Gaploid** [comment]
Hmm, It seems I`ve setup env variable in start tasks for tasks. I will try pool start task.

**Comment by timotheeguerin** [comment]
did that work for you?

**Comment by Gaploid** [comment]
Yep, its working!
