### ISSUE TITLE
No Metrics Showing

### ISSUE THREAD

**Issue by SharmainePopov** [Azure/batch-insights#39]
Does not show performance graphs. Just the tabs for them. 

![batchmetrics](https://user-images.githubusercontent.com/34690778/59239518-be608b00-8bcf-11e9-85b1-77c889bf8712.PNG)
![batchsettings](https://user-images.githubusercontent.com/34690778/59240220-aee24180-8bd1-11e9-9b8d-43ca4a574635.PNG)

![notedstats](https://user-images.githubusercontent.com/34690778/59241504-ef43be80-8bd5-11e9-98b3-f390d350e7dd.PNG)
![stderr](https://user-images.githubusercontent.com/34690778/59241509-f5d23600-8bd5-11e9-99ad-b46adc234d2c.PNG)

**Comment by timotheeguerin** [comment]
Looks like you have a typo in the `BATCH_INSIGHTS_DOWNLOAD_UR` env variable(missing the `L`

**Comment by SharmainePopov** [comment]
Hi typo fixed but still no graphs.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by SharmainePopov** [comment]
...also same errors.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by timotheeguerin** [comment]
hhm, Same error in `stderr.txt` as well? I guess you rebooted the node(s) after the change?

**Comment by SharmainePopov** [comment]
Oh the reboot. Tripped over that before. Ok let me do that.

Sharmaine Popov
Cloud Solution Architect |Microsoft Canada Inc. | sharmaine.popov@microsoft.com<mailto:sharmaine.popov@microsoft.com> | 416-799-0807

**Comment by timotheeguerin** [comment]
In Batch Explorer after you update the start task you get a notification that lets you reboot all the nodes at once too.

**Comment by SharmainePopov** [comment]
? I have never noticed that.

Sharmaine Popov
Cloud Solution Architect |Microsoft Canada Inc. | sharmaine.popov@microsoft.com<mailto:sharmaine.popov@microsoft.com> | 416-799-0807

**Comment by timotheeguerin** [comment]
Should look like this
![image](https://user-images.githubusercontent.com/1031227/59290196-db777700-8c2c-11e9-8c2b-30a30bc0fc81.png)

**Comment by SharmainePopov** [comment]
Ok! No errors but no graphs either 😊 ☹

Sharmaine Popov
Cloud Solution Architect |Microsoft Canada Inc. | sharmaine.popov@microsoft.com<mailto:sharmaine.popov@microsoft.com> | 416-799-0807

**Comment by SharmainePopov** [comment]
Do you have a working demo? Would like to show my client something in about 15 minutes 😊

Sharmaine Popov
Cloud Solution Architect |Microsoft Canada Inc. | sharmaine.popov@microsoft.com<mailto:sharmaine.popov@microsoft.com> | 416-799-0807

**Comment by SharmainePopov** [comment]
Ok! Got graphs. Is there a way to persist this data or they can just look at the graphs??


Sharmaine Popov
Cloud Solution Architect |Microsoft Canada Inc. | sharmaine.popov@microsoft.com<mailto:sharmaine.popov@microsoft.com> | 416-799-0807

**Comment by timotheeguerin** [comment]
App insights has a delay in the metrics ~5min so would make sense nothing is there yet. I can give you read permission to an account which has test pool but graphs will look like that 
![image](https://user-images.githubusercontent.com/1031227/59290639-e252b980-8c2d-11e9-9d39-940a18245b5a.png)

**Comment by timotheeguerin** [comment]
All this data in in application insights which persit for 90 days I believe. You can query it yourself and get with specific parameters. See this doc for it https://github.com/Azure/batch-insights/wiki/Query-application-insights

**Comment by SharmainePopov** [comment]
Wait have graphs – but no CPU?
Also do you know if code can be instrumented wit App Insights to get the task run data?  I went through this article, with the accompanying code but never got anything in App Insights.
https://docs.microsoft.com/en-us/azure/batch/monitor-application-insights

Sharmaine Popov
Cloud Solution Architect |Microsoft Canada Inc. | sharmaine.popov@microsoft.com<mailto:sharmaine.popov@microsoft.com> | 416-799-0807

**Comment by timotheeguerin** [comment]
CPU should be here, what do you see? For the task specific metrics. this tool unfortunately doesn't provide this functionality. For this you'd need to have something run for every task.

**Comment by SharmainePopov** [comment]
[cid:image001.png@01D52054.E7BD6B30]

Sharmaine Popov
Cloud Solution Architect |Microsoft Canada Inc. | sharmaine.popov@microsoft.com<mailto:sharmaine.popov@microsoft.com> | 416-799-0807

**Comment by timotheeguerin** [comment]
The image doesn't show up on github or the email. Could you try uploading via github?

**Comment by timotheeguerin** [comment]
Hhm and no errors in nodestats.log or nodestats.err.log? Which OS is the pool running on?

**Comment by SharmainePopov** [comment]
Nope, I’ll send the out log later.
Can we get per node stats in log analytics

Sharmaine Popov
Cloud Solution Architect |Microsoft Canada Inc. | sharmaine.popov@microsoft.com<mailto:sharmaine.popov@microsoft.com> | 416-799-0807

**Comment by timotheeguerin** [comment]
Yes, you can query using the `roleInstance` property 

https://github.com/Azure/batch-insights/wiki/Query-application-insights#basic-list-of-all-metrics-for-a-node

**Comment by SharmainePopov** [comment]
Hi Thanks for all the help, I think the client can use this. Do you know what the data collection interval is for the performance counters?

Sharmaine Popov
Cloud Solution Architect |Microsoft Canada Inc. | sharmaine.popov@microsoft.com<mailto:sharmaine.popov@microsoft.com> | 416-799-0807

**Comment by timotheeguerin** [comment]
You can check the config options here https://github.com/Azure/batch-insights/blob/master/docs/configuration.md 

One is the local aggregation interval. By default it collect metrics every 5s, aggregate and uploads every minute(which is the minimum app insights will aggregate on. That way it reduce the amount of data uploaded to app insights and so the cost)

**Comment by SharmainePopov** [comment]
Thanks again. Any chance we can make the aggregation interval less than 1 minute - or otherwise get at the raw data?
My client is a research lab and they are going to be doing a bench mark paper, and they were hoping they could get the data the need via a cloud service rather than trying instrument the OS.


Sharmaine Popov
Cloud Solution Architect |Microsoft Canada Inc. | sharmaine.popov@microsoft.com<mailto:sharmaine.popov@microsoft.com> | 416-799-0807

**Comment by timotheeguerin** [comment]
Unfortunately even if batch-insights upload every 5s, I believe application insights will only aggregate the data in a minimum of a minute interval. You have to be carful with the cost of application insights which can become quite high with large pools if you upload too much data. You could always take this project and change it to upload to another  system(like graphana) and get the raw data this way

**Comment by SharmainePopov** [comment]
Ok – where would I start. Is this developer stuff?

Sharmaine Popov
Cloud Solution Architect |Microsoft Canada Inc. | sharmaine.popov@microsoft.com<mailto:sharmaine.popov@microsoft.com> | 416-799-0807

**Comment by timotheeguerin** [comment]
Yes you would need to fork the project and implement the data egress for another system than application insights.
