### ISSUE TITLE
Confusing CPU stats showing in Batch Labs

### ISSUE THREAD

**Issue by edwardsp** [Azure/batch-insights#4]
What is the CPU usage showing in BatchLabs?  I have 4 dedicated nodes each with 16 cores and BatchLabs shows the following:

![cpuusageinbatchlabs](https://user-images.githubusercontent.com/905229/35215518-6672a4ce-ff5c-11e7-97a2-c3751b435fdd.PNG)

I don't understand what the 10 CPUs are referring to.

**Comment by dkreg** [comment]
I've noticed something similar for a multi-instance (mpi) task running across two nodes, with one core per node. Batch labs/app insights only displays the cpu usage for one cpu. Presumably this is the same bug.

**Comment by timotheeguerin** [comment]
@dkreg It sounds like it shows as intended. The cpus showing are cores of the nodes so if node. So if you have a 1 core node it will only show 1 cpu, if 2 it will show 2. Then the line is the average of the 1st, 2nd, etc cpu of all the nodes
This stats is confusing and I'll be working to remove it and add some alternative.

**Comment by timotheeguerin** [comment]
I removed the individual cpu from batchlabs when looking at the pool stats, will show on the node stats(Coming in version 0.14.0 probably in about a week)
