### ISSUE TITLE
How Do I view Batch-Insights metrics from the Azure Portal?

### ISSUE THREAD

**Issue by jkindwall** [Azure/batch-insights#42]
From the ReadMe:

> Option 2:
> Use the app insights tools to build your own query on the Azure Portal

Is there any documentation anywhere on how exactly to do that?  Batch-Explorer is a nice tool, but the graphs aren't very flexible and the scaling is a little wonky.  AppInsights in the Azure Portal seems to have a lot more options, but I can't seem to find a way to get to the data logged by the Batch-Insights tool.

**Comment by timotheeguerin** [comment]
There is some information on a few queries you can write here. For that
https://github.com/Azure/batch-insights/wiki/Query-application-insights
